redis:
        docker compose exec redis redis-cli

sh:
        docker compose exec wx-auth-server sh

pull:
        docker compose pull

up:
        docker compose up -d

down:
        docker compose down